### ISSUE TITLE
Include baseblock with Flightdata

### ISSUE THREAD

**Issue by Ierlandfan** [ianrenton/planesailing#1]
Hi Ian,

I was also looking for a uncluttered frontend so I modified a script for an ESP8266 but it's not reliable.
Woudl it be a lot of work to include the baseblock from this picture? (The part that show "Type", Altitude, etc. etc.
Can you give me some pointers?

[http://irishharvest.nl/Images/PlaneSpotter.jpg](url)

**Comment by ianrenton** [comment]
Hi, I think it depends how much of that you want to add.

Adding a new panel at the bottom of the screen is relatively easy - see the existing CSS for placing panels at the bottom, then you just need to lay out your new panel.

Getting _some_ of the data about the selected entity into that panel is also relatively easy. You probably want a regular update thread that calls a new method, similar to the existing `updateMap()`. That method would then check which entity is selected (`selectedEntityUID`), fetch that entity from the list (e.g. `var e = entities.get(selectedEntityUID);`) then you can pull out the data and update the elements in the DOM inside your new panel using jQuery (e.g. `$("#myAltitudeField").text(e.altitude);`).

The more difficult things are the "From" and "To" airports, and the photo of the plane. That's because this information isn't encoded in ADS-B and isn't available from Dump1090 directly. To look up those, you would have to use the API of a website like FlightRadar24 or FlightAware. That's not something I've tried myself so I'm not sure how it's normally done (and if it can be done for free!) Is the software in your photo open source? If so, the best approach might be to look at its source code and see where it gets airport and photo information from.

Hope that helps, let me know if you need any more help!

**Comment by Ierlandfan** [comment]
Thanx for the answer!

I actually want to use json data from adsbexchange or similar sites for data. They hold "from" and "to" and a lot of other values so that would not be a big problem. It's the "get the data to show up in the website part"

Step 1. Add panel "dataPanel" to bottom in style.css. (wip)
Step 2. Something along the line for the code would be:

```
updatedataPanel() 
entities.forEach(function(e) {
if (e.uid == selectedEntityUID) {
$("#myAltitudeField").text(e.altitude);)
...other relevant fields...
}
});
```
Step 3. Somehow add that value to the dataPanel

**Comment by ianrenton** [comment]
OK, if you're getting data from ADS-B Exchange then you're right, you'll likely get that information for free.

Your code should work, although doing the `forEach` is a bit less efficient than just using `entities.get(id)`. `entities` is a map rather than a list, so you can retrieve the specific entry you want by using the id as a key.

The jQuery line in your code (`$("#myAltitudeField")...`) adds the value to the data panel. So for example if you add the following to the HTML:

```html
<div id="dataPanel">
  <p>Altitude: <span id="myAltitudeField"></span></p>
</div>
```

Then the following in the JavaScript:

```js
function updateDataPanel() {
  var e = entities.get(selectedEntityUID);
  if (e && e.altitude) {
    $("#myAltitudeField").text(e.altitude);
  } else {
    $("#myAltitudeField").text("---");
  }
}
setInterval(updateDataPanel, 1000);
```

That should be enough for a working example. (I haven't tested it though!)

You may also be interested in the code for Plane Sailing's predecessor, UMID1090 - that has a "track table" that is populated with similar data: https://github.com/ianrenton/umid1090/blob/master/code.js#L742  It's not quite the same as what you're doing, because it builds a large table of data from all entities rather than just the selected one, but you can see the same approach being used: for each entity, it gets the data fields it's interested in, formats them into HTML, and writes the new table into the DOM using jQuery.

**Comment by Ierlandfan** [comment]
I see how it all fits together! (Your example code works)
I was thinking if I use that track table and somehow show only the data from selected flight I can reuse it. (If possible)
Since it's already a table it's easy to style . 
Then I only have to insert that data into the a new bottom panel and I think that's exactly what I need for a start.

**Comment by ianrenton** [comment]
Yes, that should work and is probably a good start!

One problem you might find later is that if you're including the photo of the aircraft, and updating the whole panel at once as a table, you might see some flickering. If that's the case, you might want to change to only updating certain parts of it rather than the whole table - e.g. the photo won't change every second, only when you click on a different plane, so you may want to update that separately.

I'll close this issue now because it isn't really a bug report/feature request for Plane Sailing, but I'd love to see how you get on - and if you have any more questions, feel free to carry on this thread!
